// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google_play_auth_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class GooglePlayAuthService
{
  static readonly string __ServiceName = "GooglePlayAuthService";

  static readonly grpc::Marshaller<global::GooglePlayLoginReq> __Marshaller_GooglePlayLoginReq = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GooglePlayLoginReq.Parser.ParseFrom);
  static readonly grpc::Marshaller<global::GooglePlayLoginResp> __Marshaller_GooglePlayLoginResp = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GooglePlayLoginResp.Parser.ParseFrom);

  static readonly grpc::Method<global::GooglePlayLoginReq, global::GooglePlayLoginResp> __Method_GooglePlayLogin = new grpc::Method<global::GooglePlayLoginReq, global::GooglePlayLoginResp>(
      grpc::MethodType.Unary,
      __ServiceName,
      "GooglePlayLogin",
      __Marshaller_GooglePlayLoginReq,
      __Marshaller_GooglePlayLoginResp);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::GooglePlayAuthServiceReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of GooglePlayAuthService</summary>
  [grpc::BindServiceMethod(typeof(GooglePlayAuthService), "BindService")]
  public abstract partial class GooglePlayAuthServiceBase
  {
    public virtual global::System.Threading.Tasks.Task<global::GooglePlayLoginResp> GooglePlayLogin(global::GooglePlayLoginReq request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for GooglePlayAuthService</summary>
  public partial class GooglePlayAuthServiceClient : grpc::ClientBase<GooglePlayAuthServiceClient>
  {
    /// <summary>Creates a new client for GooglePlayAuthService</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    public GooglePlayAuthServiceClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for GooglePlayAuthService that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    public GooglePlayAuthServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    protected GooglePlayAuthServiceClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    protected GooglePlayAuthServiceClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    public virtual global::GooglePlayLoginResp GooglePlayLogin(global::GooglePlayLoginReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GooglePlayLogin(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual global::GooglePlayLoginResp GooglePlayLogin(global::GooglePlayLoginReq request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_GooglePlayLogin, null, options, request);
    }
    public virtual grpc::AsyncUnaryCall<global::GooglePlayLoginResp> GooglePlayLoginAsync(global::GooglePlayLoginReq request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return GooglePlayLoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    public virtual grpc::AsyncUnaryCall<global::GooglePlayLoginResp> GooglePlayLoginAsync(global::GooglePlayLoginReq request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_GooglePlayLogin, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    protected override GooglePlayAuthServiceClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new GooglePlayAuthServiceClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static grpc::ServerServiceDefinition BindService(GooglePlayAuthServiceBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_GooglePlayLogin, serviceImpl.GooglePlayLogin).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  public static void BindService(grpc::ServiceBinderBase serviceBinder, GooglePlayAuthServiceBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_GooglePlayLogin, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GooglePlayLoginReq, global::GooglePlayLoginResp>(serviceImpl.GooglePlayLogin));
  }

}
#endregion
